name: Pristine_Screen
description: A basic Screen Cleaner application made to turn screen black, and lock keyboard for ease of use for cleaning.

publish_to: 'App Store'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  desktop_window: ^0.4.0
  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Museo Moderno
      fonts:
        - asset: fonts/museoModerno.ttf

  uses-material-design: true
